version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: