"""initial

Revision ID: 0e63cae788a5
Revises: 
Create Date: 2025-01-08 14:58:54.512247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e63cae788a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('domain', sa.String(length=150), nullable=False),
    sa.Column('verdict', sa.Enum('legit', 'spam', 'malware', name='verdictenum'), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources')
    # ### end Alembic commands ###
